### PR TITLE
Added Learner employability skills specs

### PR DESCRIPTION
**Pull request by bharaatt**

### CODE REVIEW

**Review by natclamp-moj — APPROVED** [review]
Looks good to me

**Comment by natclamp-moj** [comment]
I'm happy to merge this if you're happy @rj-adams

**Comment by rj-adams** [comment]
Type in line 284

operationId: **getEmployabiltiySkills**

**Comment by rj-adams** [comment]
Parameters for activity start and end date. If one of these is entered, how is the data filtered?

**Comment by bharaatt** [comment]
> Parameters for activity start and end date. If one of these is entered, how is the data filtered?

It will fetch all records matching that day i.e. activityStartDate will fetch all records exact matching with Activity start date.
Let me know if that helps

**Comment by rj-adams** [comment]
> > Parameters for activity start and end date. If one of these is entered, how is the data filtered?
> 
> It will fetch all records matching that day i.e. activityStartDate will fetch all records exact matching with Activity start date.
> Let me know if that helps

RJA - I can't think of a situation where date filters would be used in this way - more broadly, the activitystart and activityend dates don't make much sense for employability skills anyway. I think it would be best to leave the date filters out of the API as they will add unnecessary noise.

**Comment by rj-adams** [comment]
I have confirmed the status regarding filters with the team - Please remove the activityStart and activityEnd filters from this endpoint - they have no meaning and merely add complexity

**Review by rj-adams — CHANGES_REQUESTED** [review]
Remove activityStartDate and activityEndDate filters

**Review by rj-adams — APPROVED** [review]
All Good

**Comment by rj-adams** [comment]
All good

**Pull request merged**
